### ISSUE TITLE
Issue w/ Keycard Permissions + Custom Ammo Limits not working

### ISSUE THREAD

**Issue by Oxygen556** [rayzerbrain/ItemUtils#4]
I'm currently using EXILED 5.0-beta.5

Keycard Issues:
- Plugin is interfering with SCP's default keycard permissions (can't open checkpoints without cheating in and holding out a keycard).
- The config "can_be_used_remotely" also doesn't seem to work as well.
Side Note: Could you also note down all 10 keycard permission name entries? I can't seem to find the names in EXILED's #resources channel.

Armor Issues:
- The config "ammo_limit_multis" isn't affecting in-game values, I've tried using both "Nato9, Nato556", and "Ammo9x19, Ammo556x45" and none seem to work.

I understand that this is an initial release, and I appreciate your work in the configs that do properly work; such as the weapon damage multipliers, custom item sizes, and selective infinite radio battery.

**Comment by rayzerbrain** [comment]
Thank you for reporting, I definitely wouldn't have caught those by myself. These should work correctly in a build I will release a few minutes from now. I realized the way the config was set up was inefficient and also didn't work for multiple items, so you'll have to refactor a little if you already have configuration set up. Also, the keycard permissions are in the resources channel, on a post of january 16th.
