### ISSUE TITLE
"ammo_limit_multis" issue update

### ISSUE THREAD

**Issue by Oxygen556** [rayzerbrain/ItemUtils#5]
Hey, it's Oxygen again.

I did a couple days worth of testing with populated lobbies, and I found out how ammo limits for the armors was working.

Turns out config isn't affecting the actual limit on how much ammo you can pick up, but if you can keep the ammo after deloading a firearm.

Example:
- I have heavy armor on and I have 200 556x45mm rounds and a full-cap E11.
- I set the multiplier for ammo limits to, let's say 10.
- If I try to pick up more ammo, the game prompts me I can't pick up ammo.
- HOWEVER, if I deload the E11, I now have 231 rounds but when I drop the rifle, I keep the ammo in my inventory instead of the server automatically dropping the extra bullets.
- This method can be repeated over and over again, but you can't pick up ammo boxes of stated caliber unless going back under the native ammo limit.

I don't know if you already knew this or not, and I'm pretty sure you intended the effect to boost native limits, but that's just how the feature is currently working right now.

(I'm still using EXILED 5.0 beta.5)

**Comment by rayzerbrain** [comment]
Weird, I tested it the other day and it seemed to work (albeit in weird ways), but now when I test it it's like you describe. 

Right now Exiled's built in property for ammo limits doesn't seem to be working, at least not in the way I'm using it. I'll have to find a workaround, which could take some time, and probably won't be as pretty code-wise, unless I can resolve something with Exiled's API.

**Comment by rayzerbrain** [comment]
Ok, it looks like the client has it's own ammo limit check on picking up ammo which stops the server from doing any validation to allow me to override it, and I can't get the client's limit to sync to the server one (of the plugin). As long as this is the case, ammo limits won't work when picking up excess ammo.

I'll leave it in the list of modifiers in case this ever changes, but it seems unlikely.
