### ISSUE TITLE
plz add weight and length item modifiers

### ISSUE THREAD

**Issue by KrappyKraberMain** [rayzerbrain/ItemUtils#6]
can you add the weight and length stats to the plugin's item modifiers? (Weight affects both sprinting speed/duration and hipfire accuracy/running accuracy while length only affects hipfire accuracy/running accuracy, apparently). idk if you can, but it would be very cool if you did!

**Comment by rayzerbrain** [comment]
It's possible, it would take a good amount of workaround compared to the other modifiable parameters. I'll look into it when I have the chance

**Comment by KrappyKraberMain** [comment]
chad

**Comment by rayzerbrain** [comment]
Now implemented

**Comment by KrappyKraberMain** [comment]
mega chad
